/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e2e2e2",
        "on-secondary-fixed-variant": "#3a4c2d",
        "tertiary": "#586152",
        "surface-variant": "#e2e2e2",
        "surface-tint": "#3e690d",
        "inverse-surface": "#2f3131",
        "on-error": "#ffffff",
        "surface-container": "#eeeeee",
        "surface": "#f9f9f9",
        "on-tertiary-fixed-variant": "#41493c",
        "on-primary-fixed": "#0e2000",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#c0c9b7",
        "secondary-fixed-dim": "#b8cda5",
        "primary-fixed": "#bdf288",
        "primary-container": "#76a646",
        "secondary-container": "#d1e7bd",
        "on-secondary-container": "#566847",
        "tertiary-fixed": "#dce6d3",
        "outline-variant": "#c3c9b6",
        "surface-dim": "#dadada",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "outline": "#737969",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "surface-bright": "#f9f9f9",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#43493b",
        "tertiary-container": "#929b8a",
        "on-primary-container": "#1c3700",
        "on-tertiary-fixed": "#161e12",
        "error-container": "#ffdad6",
        "primary": "#3e690d",
        "secondary-fixed": "#d4e9bf",
        "on-background": "#1a1c1c",
        "surface-container-high": "#e8e8e8",
        "primary-fixed-dim": "#a2d56f",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#2b3326",
        "on-secondary-fixed": "#101f06",
        "inverse-primary": "#a2d56f",
        "inverse-on-surface": "#f1f1f1",
        "on-primary-fixed-variant": "#2b5000",
        "background": "#f9f9f9",
        "secondary": "#516443",
        "surface-container-low": "#f3f3f3"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        headline: ["Gill Sans Medium", "Gill Sans", "Trebuchet MS", "sans-serif"],
        body: ["Gill Sans Medium", "Gill Sans", "Trebuchet MS", "sans-serif"],
        label: ["Gill Sans Medium", "Gill Sans", "Trebuchet MS", "sans-serif"],
      },
    },
  },
  plugins: [],
}